repos:
  # import formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  # AI based foramtter, improves readability
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.13.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --in-place, --no-summary]

  # Code foramtter for both python files and jupyter notebooks
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
      - id: black
        language_version: python3.10

  # type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy

  # additional hooks found with in the pre-commit lib
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
