repos:
   # remove unused imports
  - repo: https://github.com/hadialqattan/pycln.git
    rev: v2.1.3
    hooks:
      - id: pycln

  # import formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # Code formatter for both python files and jupyter notebooks
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
      - id: black
        language_version: python3.10

  # AI based formatter, improves readability
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.13.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --in-place, --no-summary]

  # python linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.245'
    hooks:
      - id: ruff

  #  additional hooks found with in the pre-commit lib
  # -- remove trailing spaces
  # -- remove mix line ending (tabs and spaces)
  # -- JSON formatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"

