repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/sourcery-ai/sourcery
  rev: v0.13.0
  hooks:
  - id: sourcery
    args: [--diff=git diff HEAD, --in-place, --no-summary]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3.10