"""
-*- coding: utf-8 -*-

Form implementation generated from reading ui file 'macstr.ui'

Created by: PyQt5 UI code generator 5.15.9

WARNING: Any manual changes made to this file will be lost when pyuic5 is
run again.  Do not edit this file unless you know what you are doing.

stock img source:
https://commons.wikimedia.org/wiki/File:PC3_cell.jpg
"""
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cell_img1 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img1.setGeometry(QtCore.QRect(30, 10, 221, 191))
        self.cell_img1.setText("")
        self.cell_img1.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img1.setScaledContents(True)
        self.cell_img1.setProperty("img_id", 1)
        self.cell_img1.setObjectName("cell_img1")
        self.cell_img2 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img2.setGeometry(QtCore.QRect(280, 10, 221, 191))
        self.cell_img2.setText("")
        self.cell_img2.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img2.setScaledContents(True)
        self.cell_img2.setProperty("img_id", 2)
        self.cell_img2.setObjectName("cell_img2")
        self.cell_img3 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img3.setGeometry(QtCore.QRect(530, 10, 221, 191))
        self.cell_img3.setText("")
        self.cell_img3.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img3.setScaledContents(True)
        self.cell_img3.setProperty("img_id", 3)
        self.cell_img3.setObjectName("cell_img3")
        self.cell_img4 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img4.setGeometry(QtCore.QRect(30, 260, 221, 191))
        self.cell_img4.setText("")
        self.cell_img4.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img4.setScaledContents(True)
        self.cell_img4.setProperty("img_id", 4)
        self.cell_img4.setObjectName("cell_img4")
        self.cell_img5 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img5.setGeometry(QtCore.QRect(280, 260, 221, 191))
        self.cell_img5.setText("")
        self.cell_img5.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img5.setScaledContents(True)
        self.cell_img5.setProperty("img_id", 5)
        self.cell_img5.setObjectName("cell_img5")
        self.cell_img6 = QtWidgets.QLabel(self.centralwidget)
        self.cell_img6.setGeometry(QtCore.QRect(530, 260, 221, 191))
        self.cell_img6.setText("")
        self.cell_img6.setPixmap(QtGui.QPixmap("cell-images.jpg"))
        self.cell_img6.setScaledContents(True)
        self.cell_img6.setProperty("img_id", 6)
        self.cell_img6.setObjectName("cell_img6")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(350, 510, 83, 25))
        self.refresh_btn.setObjectName("refresh_btn")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(90, 210, 83, 25))
        self.btn1.setDefault(False)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(350, 210, 83, 25))
        self.btn2.setProperty("button_id", 2)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(590, 210, 83, 25))
        self.btn3.setProperty("button_id", 3)
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(90, 460, 83, 25))
        self.btn4.setProperty("button_id", 4)
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(350, 460, 83, 25))
        self.btn5.setProperty("button_id", 5)
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(590, 460, 83, 25))
        self.btn6.setProperty("button_id", 6)
        self.btn6.setObjectName("btn6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MacStr"))
        self.refresh_btn.setText(_translate("MainWindow", "Reload"))
        self.refresh_btn.setProperty(
            "button_id", _translate("MainWindow", "reload")
        )
        self.btn1.setText(_translate("MainWindow", "No Striation"))
        self.btn1.setProperty("button_id", _translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "No Striation"))
        self.btn3.setText(_translate("MainWindow", "No Striation"))
        self.btn4.setText(_translate("MainWindow", "No Striation"))
        self.btn5.setText(_translate("MainWindow", "No Striation"))
        self.btn6.setText(_translate("MainWindow", "No Striation"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    # executing app
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
