name: macrophage-striation-tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  coordinate_tests-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: smartdada2
          environment-file: env.yaml
      - run: |
          pip install -e .
          cd src/testing
          python -m unittest test_coordinates
  coordinate_tests-MacOS:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: smartdada2
          environment-file: env.yaml
      - run: |
          pip install -e .
          cd src/testing
          python -m unittest test_coordinates
  coordinate_tests-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: smartdada2
          environment-file: env.yaml
      - run: |
          pip install -e .
          cd src/testing
          python -m unittest test_coordinates
